#title: nnunn
email: natasha@nnunn.ca
description: >-
  Writing. Gardening. Tarot. Yoga. 
baseurl: ""
url: "http://nnunn.ca"
twitter_username: nnunny
github_username:  nnunn
excerpt_separator: <!--more-->

# Build settings
plugins:
  - jekyll-feed
  
include: ["archive"]

# Keep posts in archive folder and generate URLs correctly
defaults:
  - scope:
      path: "archive"
    values:
      permalink: /archive/:categories/:year/:month/:day/:title:output_ext