title: nnunn
email: natasha@nnunn.ca
description: >-
  Writing. Gardening. Tarot. Yoga. 
baseurl: ""
url: "http://nnunn.ca"
twitter_username: nnunny
github_username:  nnunn
excerpt_separator: <!--more-->

# Build settings
plugins:
  - jekyll-feed
  
include: ["archive"]